In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Read the data to python environment
df1=pd.read_csv("Sales_add_d07dcf3151ab92c468dc132ede54bda5.csv")
df1

Month      Region      Manager  Sales_before_digital_add(in $)  \
0    Month-1  Region - A  Manager - A                          132921   
1    Month-2  Region - A  Manager - C                          149559   
2    Month-3  Region - B  Manager - A                          146278   
3    Month-4  Region - B  Manager - B                          152167   
4    Month-5  Region - C  Manager - B                          159525   
5    Month-6  Region - A  Manager - B                          137163   
6    Month-7  Region - C  Manager - C                          130625   
7    Month-8  Region - A  Manager - A                          131140   
8    Month-9  Region - B  Manager - C                          171259   
9   Month-10  Region - C  Manager - B                          141956   
10  Month-11  Region - B  Manager - C                          159339   
11  Month-12  Region - A  Manager - A                          178939   
12  Month-13  Region - B  Manager - A                          145062   
13  Month-14  Region - A  Manager - A                          151514   
14  Month-15  Region - C  Manager - A                          147463   
15  Month-16  Region - A  Manager - B                          177195   
16  Month-17  Region - A  Manager - C                          140862   
17  Month-18  Region - C  Manager - B                          167996   
18  Month-19  Region - B  Manager - A                          132135   
19  Month-20  Region - A  Manager - B                          152493   
20  Month-21  Region - B  Manager - A                          147425   
21  Month-22  Region - A  Manager - C                          130263   

    Sales_After_digital_add(in $)  
0                          270390  
1                          223334  
2                          244243  
3                          231808  
4                          258402  
5                          256948  
6                          222106  
7                          230637  
8                          226261  
9                          193735  
10                         203175  
11                         276279  
12                         205180  
13                         253131  
14                         229336  
15                         187305  
16                         234908  
17                         191517  
18                         227040  
19                         212579  
20                         263388  
21                         243020

In [3]:
# Identify the columns
df1.columns

Index(['Month', 'Region', 'Manager', 'Sales_before_digital_add(in $)',
       'Sales_After_digital_add(in $)'],
      dtype='object')

In [4]:
# Check the null values
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 5 columns):
 #   Column                          Non-Null Count  Dtype 
---  ------                          --------------  ----- 
 0   Month                           22 non-null     object
 1   Region                          22 non-null     object
 2   Manager                         22 non-null     object
 3   Sales_before_digital_add(in $)  22 non-null     int64 
 4   Sales_After_digital_add(in $)   22 non-null     int64 
dtypes: int64(2), object(3)
memory usage: 1008.0+ bytes


In [5]:
df1.describe()

Sales_before_digital_add(in $)  Sales_After_digital_add(in $)
count                       22.000000                      22.000000
mean                    149239.954545                  231123.727273
std                      14844.042921                   25556.777061
min                     130263.000000                  187305.000000
25%                     138087.750000                  214960.750000
50%                     147444.000000                  229986.500000
75%                     157627.500000                  250909.000000
max                     178939.000000                  276279.000000

### 1.The company wishes to clarify whether there is any increase in sales after stepping into digital marketing.

#### Here we have to check whether there is any increase in sales after stepping into digital marketing.
#### **Ho:The sales before digital marketing and the sales after digital marketing are the same.**
#### **H1:The sales before digital marketing is less than the sales after digital marketing.**

In [6]:
from scipy import stats
t_value,p_value=stats.ttest_ind(df1["Sales_before_digital_add(in $)"],df1["Sales_After_digital_add(in $)"],alternative ='less')
t_value,p_value
print('P value is=',p_value)
print('Test statistic is=',t_value)
if p_value<0.05:
    print('null hypothesis is rejected')
else:
     print('null hypothesis is not rejected')

P value is= 1.3071840034523225e-16
Test statistic is= -12.995084451110877
null hypothesis is rejected


#### Here we reject Ho, i.e,The sales before digital marketing is less than the sales after digital marketing.
#### So there is an increase in sales after stepping into digital marketing.


### 2. The company needs to check whether there is any dependency between the features “Region” and “Manager”.

#### Here we have to check whether there is  any dependency between the features “Region” and “Manager”.
#### Ho:There is no relationship between the features “Region” and “Manager”.
#### H1:There is a relationship between the features “Region” and “Manager”.

In [7]:
contigency_table=pd.crosstab(df1["Region"],df1["Manager"])
print('contigency_table :-\n',contigency_table)

contigency_table :-
 Manager     Manager - A  Manager - B  Manager - C
Region                                           
Region - A            4            3            3
Region - B            4            1            2
Region - C            1            3            1


In [8]:
observed_values=contigency_table.values
print("Observed Values :-\n",observed_values)

Observed Values :-
 [[4 3 3]
 [4 1 2]
 [1 3 1]]


In [9]:
b=stats.chi2_contingency(contigency_table)
Expected_Values=b[3]
print("Expected Values :\n",Expected_Values)

Expected Values :
 [[4.09090909 3.18181818 2.72727273]
 [2.86363636 2.22727273 1.90909091]
 [2.04545455 1.59090909 1.36363636]]


In [10]:
no_of_rows=len(contigency_table.iloc[0:3,0])
no_of_columns=len(contigency_table.iloc[0,0:3])
ddof=(no_of_rows-1)*(no_of_columns-1)
print("Degree of Freedom:-",ddof)
alpha=0.05

Degree of Freedom:- 4


In [11]:
from scipy.stats import chi2
chi_square=sum([(o-e)**2./e for o,e in zip(observed_values,Expected_Values)])
chi_square_statistic=chi_square[0]+chi_square[1]
print("chi-square statistic:-",chi_square_statistic)

chi-square statistic:- 2.921995464852608


In [12]:
critical_value=chi2.ppf(q=1-alpha,df=ddof)
print('critical_value:',critical_value)

critical_value: 9.487729036781154


In [20]:
if chi_square_statistic>=critical_value:
    print("Reject Ho,There is a relationship between 2 catergorical variables")
else:
    print("Accept Ho,There is no relationship between 2 catergorical variables")

Accept Ho,There is no relationship between 2 catergorical variables


In [18]:
p_value=1-chi2.cdf(x=chi_square_statistic,df=ddof)
print('p-value:',p_value)

p-value: 0.5709629929220089


In [21]:
if p_value<=alpha:
    print("Reject Ho,There is a relationship between 2 catergorical variables")
else:
    print("Accept Ho,There is no relationship between 2 catergorical variables")

Accept Ho,There is no relationship between 2 catergorical variables


#### Here we accept Ho i.e,There is no relationship between the features “Region” and “Manager”.
#### So there is no dependency between the features “Region” and “Manager”.
#### i.e,The features “Region” and “Manager" are independent.